joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.07
    autorepeat_rate: 0.0
    coalesce_interval_ms: 5

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 2.0
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 2.0
    
    enable_button: 6
    enable_turbo_button: 7

    require_enable_button: true